"""empty message

Revision ID: 49f749ff4b13
Revises: c096503827ae
Create Date: 2023-11-01 11:28:32.867363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f749ff4b13'
down_revision = 'c096503827ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_configurations',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('device_id', sa.String(length=255), nullable=False),
                    sa.Column('app_config_uri', sa.String(length=512), nullable=False),
                    sa.Column('depth_config_uri', sa.String(length=512), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('device_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_configurations')
    # ### end Alembic commands ###
